# Generated by Django 2.2.5 on 2019-09-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_hebergement',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
