# Generated by Django 2.2.5 on 2019-09-25 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20190924_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
